language: php
php:
  - '7.0'
script:
  - echo 'this is a static site not an app'
deploy:
  provider: heroku
  buildpack: php
  api_key:
    secure: NDdW4DZ9j+QHHZaRJdrpO0bBlAGpfvSTxCD/BDMcfhkrMzbLVic0894kdpOoyIR5aaMR/FJJEYE/HnVvcIXWEfJ+xV9xZ6ZZcy7c35liQTRDOGCxKRI0jsYkEzubdvPj0TypptIbsNMYSN7TZ7B+FHOmZPET7V7WZ7mODZSJ/WdzaI7tUrEzQfMlGGzKAehv3K34thLFBstGELpnnxQgoFMpGnDtOYirJhWt/FOB2DL7OjA3BbHe18V4ddx/zCKmgArbNVf0GmR59ln7a9/eLc0yaQ2f8QDHBoLRdSsMfNq9oTNjskLgC6IOu3JJj3dF8AeW0jRInAkPxO2WgPOsVymv7MGZVUGrrgTD6Zi1mHNMVX/dXGGnaK+q9CCDmvxoxraRkRZMCAvr4KUP2bL0q29peNKcDIdaIxCuJiwlX+X6kQGwET73dBOuLOeXX6dIr2UQjG89FJowiTA2zzENzDBOXF+dZGgEB91NNUNy/NBZ5klcIjXmn5yXJM9HAEssrx6tW2nMm+/RfCnxM4siWjvXuZ8E2+iNokNRpudM7eH+QaxS6uuq55t9Oyv/VO6V4mQ2wCTxXsFRFoS5gpUKFHT/6fkhzL5flp9ZlHGbhntk6Ah5Ierxna2TTzlWMkd2/TgnEAnlvXlZN2v5jG6++Uh1Sgk3jjZwvAQr61z5WxA=
  app:
    production: remote-pyladies
    staging: pyladies-remote-staging
  on:
    repo: pyladies-remote/website
    branch: production
